// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywxbxkdlnydbubxgdzuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eGJ4a2RsbnlkYnVieGdkenV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzY0NDgsImV4cCI6MjA3MjcxMjQ0OH0.2moGi_dTkPOE1CgnD3uf0L9V6yGgzB9Xj6L4u6e-eOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});